### ISSUE TITLE
TypeError: application.register is not a function

### ISSUE THREAD

**Issue by miharekar** [hotwired/stimulus#443]
I opened [this issue](https://github.com/hotwired/stimulus-rails/issues/72) in stimulus-rails, but I think it belongs here.

After upgrading from 0.4.1 to 0.4.2 I get a bunch of these in the console and, obviously, Stimulus is not working.

<img width="1272" alt="132190649-ef0e096c-c035-4190-860d-5dc79cde3a6d" src="https://user-images.githubusercontent.com/986645/132499236-f95fbb00-9211-4c15-a609-fdd2bb36eec8.png">

The browser points me to `then` line in this function:
```
function registerControllerFromPath(path, under, application) {
  const name = path
    .replace(`${under}/`, "")
    .replace("_controller", "")
    .replace(/\//g, "--")
    .replace(/_/g, "-")

  import(path)
    .then(module => application.register(name, module.default))
    .catch(error => console.log(`Failed to register controller: ${name} (${path})`, error))
};
```

My controllers that are causing this are extremely trivial, for example [avatar_controller.js](https://github.com/miharekar/decent-visualizer/blob/importmap/app/javascript/controllers/avatar_controller.js):

```
import { Controller } from "@hotwired/stimulus"

export default class extends Controller {
  static targets = ["label"]

  update(event) {
    if (event.currentTarget.files.length > 0) {
      this.labelTarget.innerHTML = event.currentTarget.files[0].name
    }
  }
}
```

**Comment by dhh** [comment]
You need to update your controllers/index setup to use the latest from the stimulus-rails generator:

```js
import { Application } from "@hotwired/stimulus"

const application = Application.start()

// Configure Stimulus development experience
application.warnings = true
application.debug    = false
window.Stimulus      = application

// Import and register all your controllers from the importmap under controllers/*
import { registerControllersFrom } from "@hotwired/stimulus-importmap-autoloader"
registerControllersFrom("controllers", application)
```

**Comment by miharekar** [comment]
Oh 🤦‍♂️

Thank you, @dhh!
